apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: system-basic-auth
  namespace: system
type: kubernetes.io/basic-auth
stringData:
  username: waoendpointproxy
  password: "#We2S!&MMhin"
